export { Main } from './main'
export { Login } from './login'
export { Register } from './register'
export { ForgotPassword } from './forgot-password'
export { ResetPassword } from './reset-password'
export { Profile } from './profile'
export { PageNotFound404 } from './page-not-found-404'
